# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = ":splat"
  status = 200
  force = true
 

  headers = Access-Control-Allow-Origin = *